package net.sigmarik.abilitymod.util;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.Items;

import java.util.Set;

public class PropSets {
    public static final Set<Block> DIRTY_BLOCKS = Set.of(
            Blocks.DIRT,
            Blocks.DIRT_PATH,
            Blocks.MUD,
            Blocks.MUDDY_MANGROVE_ROOTS,
            Blocks.FARMLAND,
            Blocks.MANGROVE_LEAVES,
            Blocks.MOSS_BLOCK,
            Blocks.MOSS_CARPET,
            Blocks.NETHER_WART_BLOCK,
            Blocks.ICE,
            Blocks.PODZOL,
            Blocks.CHORUS_FLOWER,
            Blocks.ROOTED_DIRT,
            Blocks.SCULK,
            Blocks.WARPED_NYLIUM,
            Blocks.WET_SPONGE,
            Blocks.ZOMBIE_HEAD,
            Blocks.ZOMBIE_WALL_HEAD,
            Blocks.COAL_BLOCK,
            Blocks.COAL_ORE,
            Blocks.DEEPSLATE_COAL_ORE
    );

    public static final Set<Item> IRON_ITEMS = Set.of(
            Items.ANVIL,
            Items.AXOLOTL_BUCKET,
            Items.BLAST_FURNACE,
            Items.BUCKET,
            Items.CAULDRON,
            Items.CHAIN,
            Items.CHAINMAIL_BOOTS,
            Items.CHAINMAIL_CHESTPLATE,
            Items.CHAINMAIL_HELMET,
            Items.CHAINMAIL_LEGGINGS,
            Items.CHEST_MINECART,
            Items.CHIPPED_ANVIL,
            Items.COMPASS,
            Items.CROSSBOW,
            Items.DAMAGED_ANVIL,
            Items.DEEPSLATE_IRON_ORE,
            Items.DETECTOR_RAIL,
            Items.FLINT_AND_STEEL,
            Items.FURNACE_MINECART,
            Items.HEAVY_WEIGHTED_PRESSURE_PLATE,
            Items.HOPPER,
            Items.HOPPER_MINECART,
            Items.IRON_AXE,
            Items.IRON_BARS,
            Items.IRON_BLOCK,
            Items.IRON_BOOTS,
            Items.IRON_CHESTPLATE,
            Items.IRON_DOOR,
            Items.IRON_HELMET,
            Items.IRON_HOE,
            Items.IRON_HORSE_ARMOR,
            Items.IRON_INGOT,
            Items.IRON_LEGGINGS,
            Items.IRON_NUGGET,
            Items.IRON_ORE,
            Items.IRON_PICKAXE,
            Items.IRON_SHOVEL,
            Items.IRON_SWORD,
            Items.IRON_TRAPDOOR,
            Items.LANTERN,
            Items.LAVA_BUCKET,
            Items.MILK_BUCKET,
            Items.MINECART,
            Items.PISTON,
            Items.POWDER_SNOW_BUCKET,
            Items.RAIL,
            Items.RAW_IRON,
            Items.RAW_IRON_BLOCK,
            Items.SHEARS,
            Items.SHIELD,
            Items.SMITHING_TABLE,
            Items.SOUL_LANTERN,
            Items.STICKY_PISTON,
            Items.STONECUTTER,
            Items.TNT_MINECART,
            Items.TRAPPED_CHEST,
            Items.TRIPWIRE_HOOK,
            Items.WATER_BUCKET
    );
}
